# Generated by Django 4.2.6 on 2023-12-13 07:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VillageBoundaryModel",
            fields=[
                ("state_name", models.CharField(blank=True, max_length=255)),
                (
                    "object_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="Object Id"
                    ),
                ),
                (
                    "v_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "distric",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="District"
                    ),
                ),
                (
                    "subdistric",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sub District",
                    ),
                ),
                (
                    "censusname",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Census Name",
                    ),
                ),
                (
                    "lgd_villag",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Lgd Village",
                    ),
                ),
                (
                    "level_2011",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Level 2011"
                    ),
                ),
                (
                    "tru_2011",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Tru 2011"
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VillageMappingFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_name", models.CharField(blank=True, max_length=255, null=True)),
                ("ac_no", models.IntegerField(default=99999, verbose_name="AC No")),
                (
                    "object_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Object Id"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "locality",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Locality"
                    ),
                ),
                (
                    "booth",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Booth"
                    ),
                ),
                (
                    "probable_nearby_vil_voter",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Probable Nearby Village",
                    ),
                ),
                (
                    "mandal",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Mandal"
                    ),
                ),
            ],
            options={
                "ordering": ["state_name", "ac_no"],
            },
        ),
    ]
