# Generated by Django 4.2.6 on 2023-12-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Data_Analyst", "0002_rename_distric_villageboundarymodel_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="villageboundarymodel",
            name="ac_no",
            field=models.IntegerField(blank=True, null=True, verbose_name="AC No"),
        ),
    ]
