# Generated by Django 4.2.6 on 2023-12-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Data_Analyst", "0003_villageboundarymodel_ac_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="villageboundarymodel",
            name="ac_no",
            field=models.CharField(blank=True, null=True, verbose_name="AC No"),
        ),
    ]
