# Generated by Django 4.2.6 on 2023-12-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Data_Analyst", "0004_alter_villageboundarymodel_ac_no"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="villageboundarymodel",
            options={"ordering": ["state_name", "ac_no"]},
        ),
        migrations.AlterField(
            model_name="villageboundarymodel",
            name="ac_no",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="AC No"
            ),
        ),
    ]
