# Generated by Django 4.2.6 on 2023-12-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Data_Analyst", "0005_alter_villageboundarymodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="villageboundarymodel",
            name="ac_no",
            field=models.IntegerField(blank=True, null=True, verbose_name="AC No"),
        ),
    ]
