# Generated by Django 5.0 on 2023-12-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Analyst', '0007_alter_villagemappingfile_locality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villagemappingfile',
            name='locality',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Locality'),
        ),
        migrations.AlterField(
            model_name='villagemappingfile',
            name='probable_nearby_vil_voter',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Probable Nearby Village'),
        ),
    ]
