# Generated by Django 5.0 on 2023-12-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Analyst', '0008_alter_villagemappingfile_locality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villagemappingfile',
            name='booth',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Booth'),
        ),
        migrations.AlterField(
            model_name='villagemappingfile',
            name='mandal',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Mandal'),
        ),
        migrations.AlterField(
            model_name='villagemappingfile',
            name='name',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Name'),
        ),
    ]
